import { TemplateConfig } from './types';

const SYSTEM_FONT = `-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif`;

export const TEMPLATES: TemplateConfig[] = [
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    category: 'utility',
    patterns: [/\b(convert|converter|unit|units|length|weight|temperature|volume)\b/i],
    description: 'Convert between units of length, weight, temperature, and volume',
    html: '<div class="app-container"><header><h1>Unit Converter</h1></header><main><select id="category"><option>Length</option><option>Weight</option><option>Temperature</option><option>Volume</option></select><div class="input-group"><input type="number" id="inputValue" placeholder="Enter value"><select id="fromUnit"></select></div><div class="input-group"><input type="text" id="outputValue" readonly><select id="toUnit"></select></div></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#f5f7fa,#c3cfe2);min-height:100vh}header{text-align:center;margin-bottom:2rem}h1{font-size:2rem;color:#1a1a1a;margin:0}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 10px 30px rgba(0,0,0,0.1);font-family:' + SYSTEM_FONT + '}select,input{width:100%;padding:0.75rem;border:2px solid #e0e0e0;border-radius:8px;margin-bottom:1rem;font-family:inherit}.input-group{display:grid;grid-template-columns:1fr 120px;gap:0.75rem;margin-bottom:1rem}@media (max-width:480px){.app-container{padding:1rem}main{padding:1.5rem}.input-group{grid-template-columns:1fr 100px}}',
    js: 'const units={length:{m:1,km:1000,cm:0.01,mm:0.001},weight:{kg:1,g:0.001,lb:0.454},temperature:{c:1,f:33.8,k:273.15},volume:{l:1,ml:0.001,gal:3.79}};function convertTemp(v,from,to){let c=from==="c"?v:from==="f"?(v-32)*5/9:v-273.15;return to==="c"?c:to==="f"?c*9/5+32:c+273.15}function conv(){const cat=document.getElementById("category").value.toLowerCase();const v=parseFloat(document.getElementById("inputValue").value);const from=document.getElementById("fromUnit").value;const to=document.getElementById("toUnit").value;if(isNaN(v)){document.getElementById("outputValue").value="";return}let result;if(cat==="temperature")result=convertTemp(v,from,to);else result=(units[cat][from]*v)/units[cat][to];document.getElementById("outputValue").value=result.toFixed(4)}document.getElementById("category").addEventListener("change",e=>{const cat=e.target.value.toLowerCase();document.getElementById("fromUnit").innerHTML="";document.getElementById("toUnit").innerHTML="";Object.keys(units[cat]).forEach((u,i)=>{document.getElementById("fromUnit").innerHTML+=`<option>${u}</option>`;if(i===0)document.getElementById("toUnit").innerHTML+=`<option>${u}</option>`});conv()});document.getElementById("inputValue").addEventListener("input",conv);document.getElementById("fromUnit").addEventListener("change",conv);document.getElementById("toUnit").addEventListener("change",conv);conv()'
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    category: 'utility',
    patterns: [/\b(password|passwords|pwd|generate\s+.*\bpassword)\b/i],
    description: 'Generate strong, random passwords with custom options',
    html: '<div class="app-container"><header><h1>Password Generator</h1></header><main><div class="pwd-display"><input type="text" id="passwordOutput" readonly><button id="copyBtn">Copy</button></div><div class="options"><label><input type="checkbox" id="upper" checked> Uppercase</label><label><input type="checkbox" id="lower" checked> Lowercase</label><label><input type="checkbox" id="nums" checked> Numbers</label><label><input type="checkbox" id="syms" checked> Symbols</label></div><div class="length"><label for="len">Length: <span id="lenVal">16</span></label><input type="range" id="len" min="8" max="32" value="16"></div><button id="genBtn" class="gen-btn">Generate</button></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#667eea,#764ba2);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.pwd-display{display:flex;gap:0.75rem;margin-bottom:1.5rem}input[type="text"]{flex:1;padding:1rem;border:2px solid #e0e0e0;border-radius:8px}button{padding:0.75rem 1.5rem;background:#667eea;color:#fff;border:0;border-radius:8px;cursor:pointer;font-weight:600;transition:0.3s}.pwd-display button:hover{background:#5568d3}.options{background:#f8f9fa;padding:1.5rem;border-radius:8px;margin-bottom:1.5rem}.options label{display:flex;align-items:center;margin-bottom:0.75rem;cursor:pointer}.options input[type="checkbox"]{margin-right:0.75rem;accent-color:#667eea}.length input[type="range"]{width:100%;margin-top:0.5rem}.gen-btn{width:100%;padding:1rem}.gen-btn:hover{transform:translateY(-2px);box-shadow:0 5px 20px rgba(102,126,234,0.4)}@media (max-width:480px){.app-container{padding:1rem}main{padding:1.5rem}.pwd-display{flex-direction:column}}',
    js: 'const UP="ABCDEFGHIJKLMNOPQRSTUVWXYZ",LO="abcdefghijklmnopqrstuvwxyz",NU="0123456789",SY="!@#$%^&*";function gen(){let s="";if(document.getElementById("upper").checked)s+=UP;if(document.getElementById("lower").checked)s+=LO;if(document.getElementById("nums").checked)s+=NU;if(document.getElementById("syms").checked)s+=SY;let p="";const len=parseInt(document.getElementById("len").value);for(let i=0;i<len;i++)p+=s[Math.floor(Math.random()*s.length)];document.getElementById("passwordOutput").value=p}document.getElementById("len").addEventListener("input",e=>{document.getElementById("lenVal").innerText=e.target.value;gen()});document.getElementById("genBtn").addEventListener("click",gen);document.getElementById("copyBtn").addEventListener("click",()=>{navigator.clipboard.writeText(document.getElementById("passwordOutput").value).then(()=>{const b=document.getElementById("copyBtn");b.innerText="Copied!";setTimeout(()=>b.innerText="Copy",2000)})});gen()'
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    category: 'utility',
    patterns: [/\b(qr|barcode|scan)\b/i, /\bqr\s*code\b/i],
    description: 'Generate QR codes from text or URLs',
    html: '<div class="app-container"><header><h1>QR Code Generator</h1></header><main><div class="input-sec"><label for="text">Enter Text:</label><textarea id="text" placeholder="Text or URL..."></textarea></div><div class="qr-display"><img id="qr" src="" alt="QR" style="display:none"><p id="ph">QR code appears here</p></div><button id="dlBtn" style="display:none">Download</button></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#f093fb,#f5576c);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.input-sec{margin-bottom:2rem}label{display:block;margin-bottom:0.5rem;font-weight:600}textarea{width:100%;padding:1rem;border:2px solid #e0e0e0;border-radius:8px;min-height:100px;font-family:inherit}.qr-display{display:flex;align-items:center;justify-content:center;min-height:300px;background:#f8f9fa;border-radius:8px;margin:2rem 0;padding:2rem}#qr{max-width:100%;box-shadow:0 5px 15px rgba(0,0,0,0.1)}#ph{color:#999}button{width:100%;padding:1rem;background:#f5576c;color:#fff;border:0;border-radius:8px;font-weight:600;cursor:pointer;transition:0.3s}button:hover{transform:translateY(-2px);box-shadow:0 5px 20px rgba(245,87,108,0.4)}',
    js: 'const ti=document.getElementById("text"),qr=document.getElementById("qr"),ph=document.getElementById("ph"),dl=document.getElementById("dlBtn");function gen(){const t=ti.value.trim();if(!t){qr.style.display="none";ph.style.display="block";dl.style.display="none";return}const url=`https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(t)}`;qr.src=url;qr.style.display="block";ph.style.display="none";dl.style.display="block"}ti.addEventListener("input",gen);dl.addEventListener("click",()=>{const link=document.createElement("a");link.href=qr.src;link.download="qrcode.png";link.click()})'
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    category: 'utility',
    patterns: [/\b(color|colors|picker|palette|hex|rgb)\b/i],
    description: 'Pick colors and generate palettes',
    html: '<div class="app-container"><header><h1>Color Picker</h1></header><main><div class="color-input"><label for="cp">Select Color:</label><input type="color" id="cp" value="#667eea"></div><div class="color-display"><div id="cb" class="color-box"></div><div class="color-info"><p>Hex: <span id="hex">#667eea</span> <button id="copyHex">Copy</button></p><p>RGB: <span id="rgb">rgb(102,126,234)</span> <button id="copyRgb">Copy</button></p></div></div><div class="palette"><h3>Palette</h3><div id="pal" class="pal-grid"></div><button id="genPal">Generate</button></div></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#fa709a,#fee140);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.color-input{margin-bottom:2rem}label{display:block;margin-bottom:1rem;font-weight:600}input[type="color"]{width:100%;height:80px;border:0;border-radius:8px}.color-display{display:grid;grid-template-columns:1fr 1fr;gap:1.5rem;margin:2rem 0}.color-box{border-radius:8px;box-shadow:0 5px 15px rgba(0,0,0,0.1);min-height:150px}.color-info{display:flex;flex-direction:column;justify-content:space-between}.color-info p{margin:0.5rem 0;font-size:0.9rem}.color-info button{padding:0.5rem 1rem;background:#f0f0f0;border:1px solid #ddd;border-radius:6px;cursor:pointer;font-size:0.85rem;transition:0.3s;margin-left:0.5rem}.color-info button:hover{background:#e0e0e0}.palette{border-top:2px solid #eee;padding-top:1.5rem}.palette h3{margin:0 0 1rem 0}.pal-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:0.75rem;margin-bottom:1.5rem}.pal-color{aspect-ratio:1;border-radius:8px;cursor:pointer;box-shadow:0 2px 8px rgba(0,0,0,0.1)}.pal-color:hover{transform:scale(1.05)}#genPal{width:100%;padding:0.75rem;background:#fa709a;color:#fff;border:0;border-radius:8px;font-weight:600;cursor:pointer;transition:0.3s}#genPal:hover{background:#f85282}@media (max-width:480px){.color-display{grid-template-columns:1fr}}',
    js: 'const cp=document.getElementById("cp"),cb=document.getElementById("cb"),hex=document.getElementById("hex"),rgb=document.getElementById("rgb"),pal=document.getElementById("pal"),genPal=document.getElementById("genPal");function h2r(h){const r=/^#?([a-f\\d]{2})([a-f\\d]{2})([a-f\\d]{2})$/i.exec(h);return r?{r:parseInt(r[1],16),g:parseInt(r[2],16),b:parseInt(r[3],16)}:null}function upd(c){cb.style.backgroundColor=c;hex.innerText=c;const r=h2r(c);if(!r)return;rgb.innerText=`rgb(${r.r},${r.g},${r.b})`}function genP(c){const cols=[c];for(let i=0;i<4;i++)cols.push("#"+Math.floor(Math.random()*16777215).toString(16).padStart(6,"0"));pal.innerHTML=cols.map(col=>`<div class="pal-color" style="background-color:${col}" title="${col}"></div>`).join("")}cp.addEventListener("input",e=>upd(e.target.value));genPal.addEventListener("click",()=>genP(cp.value));document.getElementById("copyHex").addEventListener("click",(e)=>navigator.clipboard.writeText(hex.innerText).then(()=>{const b=e.target;b.innerText="Copied!";setTimeout(()=>b.innerText="Copy",2000)}));document.getElementById("copyRgb").addEventListener("click",(e)=>navigator.clipboard.writeText(rgb.innerText).then(()=>{const b=e.target;b.innerText="Copied!";setTimeout(()=>b.innerText="Copy",2000)}));upd(cp.value);genP(cp.value)'
  },
  {
    id: 'habit-tracker',
    name: 'Habit Tracker',
    category: 'productivity',
    patterns: [/\b(habit|habits|track|tracker|daily|streak|routine)\b/i],
    description: 'Track daily habits with streaks and completion statistics',
    html: '<div class="app-container"><header><h1>Habit Tracker</h1></header><main><div class="input-sec"><input type="text" id="hi" placeholder="Add habit..."><button id="add">Add</button></div><div id="list"></div><div id="stats" style="display:none"><h3>Stats</h3><p>Total: <span id="tot">0</span></p><p>Today: <span id="tod">0</span></p><p>Completion: <span id="comp">0</span>%</p></div></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#a8edea,#fed6e3);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.input-sec{display:flex;gap:0.75rem;margin-bottom:2rem}input{flex:1;padding:0.75rem;border:2px solid #e0e0e0;border-radius:8px;font-family:inherit}button{padding:0.75rem 1.5rem;background:#a8edea;color:#fff;border:0;border-radius:8px;font-weight:600;cursor:pointer;transition:0.3s}button:hover{background:#88dfd8}.habit-item{background:#f8f9fa;border-radius:8px;padding:1rem;margin-bottom:1rem;display:flex;justify-content:space-between;align-items:center}.habit-info{flex:1}.habit-name{font-weight:600;color:#333}.habit-stats{font-size:0.85rem;color:#666}.actions{display:flex;gap:0.5rem}.check{width:40px;height:40px;border-radius:50%;border:2px solid #a8edea;background:#fff;cursor:pointer;transition:0.3s}.check.done{background:#a8edea;color:#fff}.del{background:#ff6b6b;color:#fff;padding:0.5rem 1rem;border:0;border-radius:6px;cursor:pointer}#stats{border-top:2px solid #eee;padding-top:1.5rem;margin-top:2rem}',
    js: 'function esc(s){const e=document.createElement("div");e.textContent=s;return e.innerHTML}function save(h){localStorage.setItem("habits",JSON.stringify(h))}function load(){return JSON.parse(localStorage.getItem("habits")||"[]")}function today(){return new Date().toISOString().split("T")[0]}function addHabit(){const n=document.getElementById("hi").value.trim();if(!n)return;const h=load();h.push({n:n,d:[]});save(h);document.getElementById("hi").value="";render()}function render(){const h=load();document.getElementById("list").innerHTML="";h.forEach((x,i)=>{const t=today();const d=x.d.includes(t);const s=x.d.length;const el=document.createElement("div");el.className="habit-item";el.innerHTML=`<div class="habit-info"><div class="habit-name">${esc(x.n)}</div><div class="habit-stats">Completed: ${s}</div></div><div class="actions"><button class="check ${d?"done":""}" data-i="${i}">${d?"✓":"○"}</button><button class="del" data-i="${i}">Del</button></div>`;document.getElementById("list").appendChild(el)});const tot=h.length;const com=h.filter(x=>x.d.includes(today())).length;const pct=tot>0?Math.round(com/tot*100):0;if(tot>0){document.getElementById("tot").innerText=tot;document.getElementById("tod").innerText=com;document.getElementById("comp").innerText=pct;document.getElementById("stats").style.display="block"}}document.getElementById("add").addEventListener("click",addHabit);document.getElementById("hi").addEventListener("keypress",e=>{if(e.key==="Enter")addHabit()});document.addEventListener("click",ev=>{if(ev.target.classList.contains("check")){const i=parseInt(ev.target.dataset.i);const h=load();const t=today();if(h[i].d.includes(t))h[i].d=h[i].d.filter(x=>x!==t);else h[i].d.push(t);save(h);render()}if(ev.target.classList.contains("del")){const i=parseInt(ev.target.dataset.i);const h=load();h.splice(i,1);save(h);render()}});render()'
  },
  {
    id: 'expense-tracker',
    name: 'Expense Tracker',
    category: 'productivity',
    patterns: [/\b(expense|expenses|spending|tracker|budget|money)\b/i],
    description: 'Track expenses by category with pie charts and totals',
    html: '<div class="app-container"><header><h1>Expense Tracker</h1></header><main><div class="input-sec"><input type="number" id="amount" placeholder="Amount" min="0"><select id="cat"><option>Food</option><option>Transport</option><option>Entertainment</option><option>Utilities</option><option>Other</option></select><button id="add">Add</button></div><div id="list"></div><div class="totals"><div>Total: <span id="tot">$0</span></div></div></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#667eea,#764ba2);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.input-sec{display:grid;grid-template-columns:1fr 1fr;gap:0.75rem;margin-bottom:2rem}input,select{padding:0.75rem;border:2px solid #e0e0e0;border-radius:8px;font-family:inherit}button{background:#667eea;color:#fff;border:0;border-radius:8px;cursor:pointer;font-weight:600;padding:0.75rem;grid-column:1/-1;transition:0.3s}button:hover{background:#5568d3}.expense-item{background:#f8f9fa;border-radius:8px;padding:1rem;margin-bottom:1rem;display:flex;justify-content:space-between;align-items:center}.exp-info{flex:1}.exp-amount{font-size:1.25rem;font-weight:600;color:#667eea}.exp-cat{font-size:0.85rem;color:#666}.del{background:#ff6b6b;color:#fff;padding:0.5rem 1rem;border:0;border-radius:6px;cursor:pointer}.totals{border-top:2px solid #eee;padding-top:1.5rem;margin-top:2rem;font-size:1.25rem;font-weight:600}',
    js: 'function save(e){localStorage.setItem("expenses",JSON.stringify(e))}function load(){return JSON.parse(localStorage.getItem("expenses")||"[]")}function render(){const e=load();document.getElementById("list").innerHTML="";let t=0;e.forEach((x,i)=>{t+=x.a;const el=document.createElement("div");el.className="expense-item";el.innerHTML=`<div class="exp-info"><div class="exp-amount">$${x.a.toFixed(2)}</div><div class="exp-cat">${x.c}</div></div><button class="del" data-i="${i}">Delete</button>`;document.getElementById("list").appendChild(el)});document.getElementById("tot").innerText="$"+t.toFixed(2)}document.getElementById("add").addEventListener("click",()=>{const a=parseFloat(document.getElementById("amount").value);const c=document.getElementById("cat").value;if(isNaN(a)||a<=0)return;const e=load();e.push({a:a,c:c});save(e);document.getElementById("amount").value="";render()});document.addEventListener("click",e=>{if(e.target.classList.contains("del")){const i=parseInt(e.target.dataset.i);const ex=load();ex.splice(i,1);save(ex);render()}});render()'
  },
  {
    id: 'bookmark-manager',
    name: 'Bookmark Manager',
    category: 'productivity',
    patterns: [/\b(bookmark|bookmarks|save|link|url)\b/i],
    description: 'Save and manage bookmarks with tags and search',
    html: '<div class="app-container"><header><h1>Bookmarks</h1></header><main><div class="input-sec"><input type="text" id="url" placeholder="URL"><input type="text" id="title" placeholder="Title"><input type="text" id="tags" placeholder="Tags"><button id="add">Save</button></div><div class="search"><input type="text" id="search" placeholder="Search..."></div><div id="list"></div></main></div>',
    css: '.app-container{max-width:600px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#f093fb,#f5576c);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.input-sec{display:grid;grid-template-columns:1fr 1fr;gap:0.75rem;margin-bottom:2rem}input{padding:0.75rem;border:2px solid #e0e0e0;border-radius:8px;font-family:inherit}button{background:#f5576c;color:#fff;border:0;border-radius:8px;cursor:pointer;font-weight:600;padding:0.75rem;grid-column:1/-1}button:hover{background:#ff3856}.search{margin-bottom:1.5rem}#search{width:100%;padding:0.75rem;border:2px solid #e0e0e0;border-radius:8px}.bookmark-item{background:#f8f9fa;border-radius:8px;padding:1rem;margin-bottom:1rem}.bm-title{font-weight:600;color:#333;margin-bottom:0.25rem}.bm-url{color:#667eea;font-size:0.9rem;margin-bottom:0.5rem;word-break:break-all}.bm-tags{font-size:0.8rem;color:#999}.bm-actions{margin-top:0.75rem}.del{background:#ff6b6b;color:#fff;padding:0.5rem 1rem;border:0;border-radius:6px;cursor:pointer;font-size:0.85rem}',
    js: 'function esc(s){const e=document.createElement("div");e.textContent=s;return e.innerHTML}function isValidUrl(u){try{const url=new URL(u);return url.protocol==="http:"||url.protocol==="https:"}catch{return false}}function save(b){localStorage.setItem("bookmarks",JSON.stringify(b))}function load(){return JSON.parse(localStorage.getItem("bookmarks")||"[]")}function render(f=""){const b=load().filter(x=>!f||x.t.includes(f)||x.u.includes(f)||x.g.includes(f));document.getElementById("list").innerHTML="";b.forEach((x,i)=>{const el=document.createElement("div");el.className="bookmark-item";const url=isValidUrl(x.u)?x.u:"#";el.innerHTML=`<div class="bm-title">${esc(x.t)}</div><div class="bm-url"><a href="${url}" target="_blank">${esc(x.u)}</a></div><div class="bm-tags">${esc(x.g)}</div><div class="bm-actions"><button class="del" data-i="${i}">Delete</button></div>`;document.getElementById("list").appendChild(el)})}document.getElementById("list").addEventListener("click",e=>{if(e.target.classList.contains("del")){const i=parseInt(e.target.dataset.i);const bm=load();bm.splice(i,1);save(bm);render(document.getElementById("search").value)}});document.getElementById("add").addEventListener("click",()=>{const u=document.getElementById("url").value.trim();const t=document.getElementById("title").value.trim();const g=document.getElementById("tags").value.trim();if(!u||!t||!isValidUrl(u))return;const b=load();b.push({u:u,t:t,g:g});save(b);document.getElementById("url").value="";document.getElementById("title").value="";document.getElementById("tags").value="";render()});document.getElementById("search").addEventListener("input",e=>render(e.target.value));render()'
  },
  {
    id: 'trivia-quiz',
    name: 'Trivia Quiz',
    category: 'game',
    patterns: [/\b(trivia|quiz|quizzes|question|questions|answer|answers|test)\b/i],
    description: 'Answer multiple choice trivia questions with scoring',
    html: '<div class="app-container"><header><h1>Trivia Quiz</h1></header><main id="main"><div id="quiz"><div class="q-info"><span id="prog">0/0</span><span id="score">Score: 0</span></div><div id="q" class="question"></div><div id="opts" class="options"></div><button id="next" style="display:none">Next</button></div><div id="result" style="display:none"><h2>Quiz Complete!</h2><p>Your Score: <span id="finalScore">0</span>%</p><button id="restart">Restart</button></div></main></div>',
    css: '.app-container{max-width:600px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#4facfe,#00f2fe);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.q-info{display:flex;justify-content:space-between;margin-bottom:2rem;font-weight:600}.question{font-size:1.25rem;margin-bottom:1.5rem;color:#333}.options{display:flex;flex-direction:column;gap:0.75rem;margin-bottom:1.5rem}.option{padding:1rem;background:#f8f9fa;border:2px solid #e0e0e0;border-radius:8px;cursor:pointer;transition:0.3s}.option:hover{border-color:#4facfe;background:#f0f7ff}.option.selected{background:#4facfe;color:#fff;border-color:#4facfe}.option.correct{background:#4caf50;color:#fff}.option.wrong{background:#ff6b6b;color:#fff}button{padding:0.75rem 1.5rem;background:#4facfe;color:#fff;border:0;border-radius:8px;cursor:pointer;font-weight:600;transition:0.3s;width:100%;margin-top:1rem}button:hover{transform:translateY(-2px);box-shadow:0 5px 15px rgba(79,172,254,0.4)}#result{text-align:center}#result h2{margin:0 0 1rem 0;color:#333}#result p{font-size:1.25rem;margin-bottom:2rem}',
    js: 'const questions=[{q:"What is the capital of France?",opts:["Paris","London","Berlin","Madrid"],a:0},{q:"Which planet is known as the Red Planet?",opts:["Venus","Mars","Jupiter","Saturn"],a:1},{q:"What is 2+2?",opts:["3","4","5","6"],a:1},{q:"Who painted the Mona Lisa?",opts:["Van Gogh","Picasso","Leonardo da Vinci","Michelangelo"],a:2}];let current=0;let points=0;let answered=false;function load(){const q=questions[current];document.getElementById("q").innerText=q.q;const opts=document.getElementById("opts");opts.innerHTML="";q.opts.forEach((o,i)=>{const btn=document.createElement("button");btn.className="option";btn.innerText=o;btn.addEventListener("click",()=>answer(i));opts.appendChild(btn)});document.getElementById("prog").innerText=`${current+1}/${questions.length}`;answered=false}function answer(i){if(answered)return;answered=true;const q=questions[current];document.querySelectorAll(".option").forEach((o,idx)=>{if(idx===q.a)o.classList.add("correct");else if(idx===i)o.classList.add("wrong")});if(i===q.a)points++;document.getElementById("next").style.display="block";document.getElementById("score").innerText=`Score: ${points}`}function nextQuestion(){current++;if(current<questions.length)load();else{document.getElementById("quiz").style.display="none";document.getElementById("result").style.display="block";document.getElementById("finalScore").innerText=Math.round(points/questions.length*100)}}document.getElementById("next").addEventListener("click",nextQuestion);document.addEventListener("keypress",e=>{if(e.key==="Enter"&&document.getElementById("next").style.display==="block")nextQuestion()});document.getElementById("restart").addEventListener("click",()=>{current=0;points=0;document.getElementById("quiz").style.display="block";document.getElementById("result").style.display="none";load()});load()'
  },
  {
    id: 'rock-paper-scissors',
    name: 'Rock-Paper-Scissors',
    category: 'game',
    patterns: [/\b(rock|paper|scissors|game|games|play|playing)\b/i],
    description: 'Play Rock-Paper-Scissors against the computer with win tracking',
    html: '<div class="app-container"><header><h1>Rock-Paper-Scissors</h1></header><main><div class="score"><div>You: <span id="pScore">0</span></div><div>Computer: <span id="cScore">0</span></div></div><div class="choices"><button class="choice" data-choice="rock">Rock</button><button class="choice" data-choice="paper">Paper</button><button class="choice" data-choice="scissors">Scissors</button></div><div id="result" class="result-box" style="display:none"><p id="outcome"></p><p id="comp">Computer chose: </p></div><button id="reset">Reset Score</button></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#f093fb,#f5576c);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.score{display:flex;justify-content:space-around;margin-bottom:2rem;font-size:1.25rem;font-weight:600}.choices{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:2rem}.choice{padding:1.5rem;border:2px solid #e0e0e0;background:#f8f9fa;border-radius:8px;cursor:pointer;font-weight:600;font-size:1rem;transition:0.3s}.choice:hover{border-color:#f5576c;transform:scale(1.05)}.choice.selected{background:#f5576c;color:#fff;border-color:#f5576c}.result-box{background:#f8f9fa;padding:1.5rem;border-radius:8px;text-align:center;margin-bottom:1.5rem;min-height:80px}.result-box p{margin:0.5rem 0}.result-box p:first-child{font-size:1.25rem;font-weight:600}#reset{width:100%;padding:0.75rem;background:#f5576c;color:#fff;border:0;border-radius:8px;cursor:pointer;font-weight:600}#reset:hover{background:#ff3856}',
    js: 'const choices=["rock","paper","scissors"];let pScore=0;let cScore=0;const pScoreEl=document.getElementById("pScore");const cScoreEl=document.getElementById("cScore");const resultBox=document.getElementById("result");const outcomeEl=document.getElementById("outcome");const compEl=document.getElementById("comp");document.querySelectorAll(".choice").forEach(btn=>{btn.addEventListener("click",e=>{const p=e.target.dataset.choice;const c=choices[Math.floor(Math.random()*3)];let outcome="";if(p===c)outcome="Draw!";else if((p==="rock"&&c==="scissors")||(p==="paper"&&c==="rock")||(p==="scissors"&&c==="paper")){pScore++;outcome="You Win!"}else{cScore++;outcome="Computer Wins!"}pScoreEl.innerText=pScore;cScoreEl.innerText=cScore;outcomeEl.innerText=outcome;compEl.innerText=`Computer chose: ${c.toUpperCase()}`;resultBox.style.display="block";document.querySelectorAll(".choice").forEach(b=>b.classList.remove("selected"));e.target.classList.add("selected")})});document.getElementById("reset").addEventListener("click",()=>{pScore=0;cScore=0;pScoreEl.innerText=0;cScoreEl.innerText=0;resultBox.style.display="none";document.querySelectorAll(".choice").forEach(b=>b.classList.remove("selected"))})'
  },
  {
    id: 'dice-roller',
    name: 'Dice Roller',
    category: 'game',
    patterns: [/\b(dice|d20|d6|roll)\b/i, /\broll\s+.*\bdice\b/i],
    description: 'Roll multiple dice, view history and probability',
    html: '<div class="app-container"><header><h1>Dice Roller</h1></header><main><div class="controls"><label for="num">Number of Dice:</label><input type="number" id="num" value="1" min="1" max="20"><label for="sides">Sides:</label><select id="sides"><option value="6">D6</option><option value="20">D20</option><option value="100">D100</option></select></div><button id="roll" class="roll-btn">Roll</button><div id="result" style="display:none"><p class="total">Total: <span id="tot">0</span></p><p class="rolls">Rolls: <span id="rolls">0</span></p></div><div class="history"><h3>History</h3><div id="hist"></div></div></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#667eea,#764ba2);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.controls{display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin-bottom:1.5rem}label{display:block;margin-bottom:0.5rem;font-weight:600}input,select{width:100%;padding:0.75rem;border:2px solid #e0e0e0;border-radius:8px;font-family:inherit}.roll-btn{width:100%;padding:1rem;background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;border:0;border-radius:8px;font-weight:600;cursor:pointer;margin-bottom:2rem;transition:0.3s}.roll-btn:hover{transform:scale(1.02);box-shadow:0 5px 20px rgba(102,126,234,0.4)}.result-box{background:#f8f9fa;padding:1.5rem;border-radius:8px;text-align:center;margin-bottom:2rem}.total{font-size:1.5rem;font-weight:600;color:#667eea}.rolls{font-size:0.95rem;color:#666}.history{border-top:2px solid #eee;padding-top:1.5rem}.history h3{margin:0 0 1rem 0}.history-item{background:#f8f9fa;padding:0.75rem;border-radius:6px;margin-bottom:0.5rem;font-size:0.9rem}',
    js: 'let history=[];function render(){const h=document.getElementById("hist");h.innerHTML="";history.slice().reverse().forEach(x=>{const el=document.createElement("div");el.className="history-item";el.innerText=`Roll ${x.n}d${x.s}: ${x.r} (total: ${x.t})`;h.appendChild(el)})}document.getElementById("roll").addEventListener("click",()=>{const n=parseInt(document.getElementById("num").value);const s=parseInt(document.getElementById("sides").value);let total=0;const rolls=[];for(let i=0;i<n;i++){const r=Math.floor(Math.random()*s)+1;rolls.push(r);total+=r}document.getElementById("tot").innerText=total;document.getElementById("rolls").innerText=rolls.join(", ");document.getElementById("result").style.display="block";history.push({n:n,s:s,r:rolls.join(", "),t:total});if(history.length>10)history.shift();render()});render()'
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    category: 'analytics',
    patterns: [/\b(bmi|weight|height|health|body)\b/i],
    description: 'Calculate BMI and health category from height and weight',
    html: '<div class="app-container"><header><h1>BMI Calculator</h1></header><main><div class="unit-toggle"><label><input type="radio" name="unit" value="metric" checked> Metric</label><label><input type="radio" name="unit" value="imperial"> Imperial</label></div><div class="inputs"><div><label for="height">Height:</label><div class="input-unit"><input type="number" id="height" placeholder="0"><span id="heightUnit">cm</span></div></div><div><label for="weight">Weight:</label><div class="input-unit"><input type="number" id="weight" placeholder="0"><span id="weightUnit">kg</span></div></div></div><div id="result" style="display:none"><div class="bmi-box"><span class="bmi-value" id="bmiVal">0</span><span class="bmi-cat" id="bmiCat">Normal</span></div></div></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#fa709a,#fee140);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.unit-toggle{display:flex;gap:2rem;margin-bottom:2rem}label{display:flex;align-items:center;cursor:pointer;font-weight:600}input[type="radio"]{margin-right:0.5rem;accent-color:#fa709a}.inputs{display:grid;grid-template-columns:1fr 1fr;gap:1.5rem;margin-bottom:2rem}.inputs label{display:block;margin-bottom:0.5rem;font-weight:600}.input-unit{display:flex;align-items:center}.input-unit input{flex:1;padding:0.75rem;border:2px solid #e0e0e0;border-radius:8px 0 0 8px;font-family:inherit}.input-unit span{padding:0.75rem 1rem;background:#f8f9fa;border:2px solid #e0e0e0;border-radius:0 8px 8px 0;border-left:0}.bmi-box{background:linear-gradient(135deg,#fa709a,#fee140);color:#fff;padding:2rem;border-radius:12px;text-align:center}.bmi-value{display:block;font-size:3rem;font-weight:bold;margin-bottom:0.5rem}.bmi-cat{display:block;font-size:1.25rem}',
    js: 'const heightInput=document.getElementById("height");const weightInput=document.getElementById("weight");const resultDiv=document.getElementById("result");const bmiValEl=document.getElementById("bmiVal");const bmiCatEl=document.getElementById("bmiCat");const heightUnitEl=document.getElementById("heightUnit");const weightUnitEl=document.getElementById("weightUnit");document.querySelectorAll("input[name=unit]").forEach(r=>{r.addEventListener("change",e=>{const m=e.target.value==="metric";heightUnitEl.innerText=m?"cm":"in";weightUnitEl.innerText=m?"kg":"lb";calculate()})});function calculate(){const u=document.querySelector("input[name=unit]:checked").value;let h=parseFloat(heightInput.value);let w=parseFloat(weightInput.value);if(!h||!w){resultDiv.style.display="none";return}let bmi;if(u==="metric")bmi=w/((h/100)**2);else bmi=(w/(h**2))*703;let cat="";if(bmi<18.5)cat="Underweight";else if(bmi<25)cat="Normal";else if(bmi<30)cat="Overweight";else cat="Obese";bmiValEl.innerText=bmi.toFixed(1);bmiCatEl.innerText=cat;resultDiv.style.display="block"}heightInput.addEventListener("input",calculate);weightInput.addEventListener("input",calculate);calculate()'
  },
  {
    id: 'savings-goal-tracker',
    name: 'Savings Goal Tracker',
    category: 'analytics',
    patterns: [/\b(savings|goal|target|money)\b/i, /\bsave\s+.*\b(goal|target)\b/i],
    description: 'Track savings progress toward a goal with time estimates',
    html: '<div class="app-container"><header><h1>Savings Goal</h1></header><main><div class="setup" id="setup"><label for="goal">Goal Amount ($):</label><input type="number" id="goal" placeholder="5000"><button id="start">Start</button></div><div class="tracker" id="tracker" style="display:none"><div class="info"><p>Goal: $<span id="goalVal">0</span></p><p>Current: $<span id="current">0</span></p></div><div class="progress-bar"><div id="progress" class="progress-fill"></div></div><div class="input-sec"><input type="number" id="deposit" placeholder="Deposit amount" min="0"><button id="addDeposit">Add</button></div><div id="deposits"></div></div></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#4facfe,#00f2fe);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.setup{display:flex;flex-direction:column}label{margin-bottom:0.5rem;font-weight:600}input{padding:0.75rem;border:2px solid #e0e0e0;border-radius:8px;margin-bottom:1rem;font-family:inherit}#start{background:#4facfe;color:#fff;border:0;cursor:pointer;font-weight:600;padding:0.75rem;border-radius:8px}.info{display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin-bottom:2rem;padding:1rem;background:#f8f9fa;border-radius:8px;text-align:center}.info p{margin:0;font-weight:600;font-size:1.1rem}.progress-bar{width:100%;height:30px;background:#e0e0e0;border-radius:15px;overflow:hidden;margin-bottom:2rem}.progress-fill{height:100%;background:linear-gradient(90deg,#4facfe,#00f2fe);width:0;transition:width 0.3s}.input-sec{display:flex;gap:0.75rem;margin-bottom:2rem}#deposit{flex:1;padding:0.75rem;border:2px solid #e0e0e0;border-radius:8px}#addDeposit{background:#4facfe;color:#fff;border:0;cursor:pointer;font-weight:600;padding:0.75rem 1.5rem;border-radius:8px}.deposit-item{background:#f8f9fa;padding:0.75rem;border-radius:6px;margin-bottom:0.5rem;font-size:0.9rem}',
    js: 'function save(d){localStorage.setItem("savingsData",JSON.stringify(d))}function load(){return JSON.parse(localStorage.getItem("savingsData")||"{}")}document.getElementById("start").addEventListener("click",()=>{const g=parseFloat(document.getElementById("goal").value);if(!g||g<=0)return;const d={goal:g,deposits:[]};save(d);document.getElementById("setup").style.display="none";document.getElementById("tracker").style.display="block";document.getElementById("goalVal").innerText=g.toFixed(2);render()});function render(){const d=load();if(!d.goal||d.goal<=0)return;const total=d.deposits.reduce((a,x)=>a+x,0);const pct=(total/d.goal)*100;document.getElementById("current").innerText=total.toFixed(2);document.getElementById("progress").style.width=Math.min(pct,100)+"%";const depDiv=document.getElementById("deposits");depDiv.innerHTML="";d.deposits.forEach((x)=>{const el=document.createElement("div");el.className="deposit-item";el.innerText=`Deposit: $${x.toFixed(2)}`;depDiv.appendChild(el)})}document.getElementById("addDeposit").addEventListener("click",()=>{const a=parseFloat(document.getElementById("deposit").value);if(!a||a<=0)return;const d=load();if(!d.deposits)d.deposits=[];d.deposits.push(a);save(d);document.getElementById("deposit").value="";render()});const d=load();if(d.goal&&d.goal>0){document.getElementById("setup").style.display="none";document.getElementById("tracker").style.display="block";document.getElementById("goalVal").innerText=d.goal.toFixed(2);render()}'
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    category: 'analytics',
    patterns: [/\b(age|birthday|birth|date|years|old)\b/i],
    description: 'Calculate exact age in years, months, and days plus countdown',
    html: '<div class="app-container"><header><h1>Age Calculator</h1></header><main><div class="input-sec"><label for="birth">Birth Date:</label><input type="date" id="birth"></div><div id="result" style="display:none"><div class="age-box"><span class="label">Age</span><span class="value" id="years">0</span></div><div class="age-box"><span class="label">Months</span><span class="value" id="months">0</span></div><div class="age-box"><span class="label">Days</span><span class="value" id="days">0</span></div><p id="nextBday"></p></div></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#a8edea,#fed6e3);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.input-sec{margin-bottom:2rem}label{display:block;margin-bottom:0.5rem;font-weight:600}input{width:100%;padding:0.75rem;border:2px solid #e0e0e0;border-radius:8px;font-family:inherit}.age-box{background:linear-gradient(135deg,#a8edea,#fed6e3);color:#fff;padding:1.5rem;border-radius:8px;text-align:center;margin-bottom:1rem}.label{display:block;font-size:0.9rem;opacity:0.9}.value{display:block;font-size:2rem;font-weight:bold}#nextBday{text-align:center;margin-top:1rem;font-weight:600;color:#333}',
    js: 'const birthInput=document.getElementById("birth");function calc(){const b=new Date(birthInput.value);if(!b||isNaN(b))return;const t=new Date();let y=t.getFullYear()-b.getFullYear();let m=t.getMonth()-b.getMonth();let d=t.getDate()-b.getDate();const days=[31,28,31,30,31,30,31,31,30,31,30,31];if(b.getFullYear()%4===0&&(b.getFullYear()%100!==0||b.getFullYear()%400===0))days[1]=29;if(d<0){m--;d+=days[b.getMonth()]}if(m<0){y--;m+=12}document.getElementById("years").innerText=y;document.getElementById("months").innerText=m;document.getElementById("days").innerText=d;const nextBday=new Date(t.getFullYear(),b.getMonth(),b.getDate());if(nextBday<t)nextBday.setFullYear(t.getFullYear()+1);const daysLeft=Math.ceil((nextBday-t)/86400000);document.getElementById("nextBday").innerText=`Next birthday in ${daysLeft} days`;document.getElementById("result").style.display="block"}birthInput.addEventListener("change",calc);'
  },
  {
    id: 'random-quote',
    name: 'Random Quote Generator',
    category: 'api',
    patterns: [/\b(quote|quotes|inspiration|inspirational)\b/i, /\bmotivat(e|ion|ional)?\b/i],
    description: 'Get random inspiring quotes from the Quotable API',
    html: '<div class="app-container"><header><h1>Random Quote</h1></header><main><div class="quote-box"><p id="quote" class="quote-text">Click to load a quote...</p><p id="author" class="quote-author">-</p></div><div class="actions"><button id="newQuote">New Quote</button><button id="copyQuote">Copy</button></div></main></div>',
    css: '.app-container{max-width:600px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#667eea,#764ba2);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.quote-box{padding:2rem;background:#f8f9fa;border-radius:8px;margin-bottom:2rem;border-left:4px solid #667eea}.quote-text{font-size:1.5rem;font-style:italic;margin:0 0 1rem 0;color:#333}.quote-author{margin:0;color:#666;text-align:right}.actions{display:flex;gap:1rem}.actions button{flex:1;padding:0.75rem;background:#667eea;color:#fff;border:0;border-radius:8px;cursor:pointer;font-weight:600;transition:0.3s}.actions button:hover{transform:translateY(-2px);box-shadow:0 5px 15px rgba(102,126,234,0.4)}',
    js: 'async function loadQuote(){try{const r=await fetch("/api/quote");if(!r.ok)throw new Error("API error");const d=await r.json();if(!d.q||!d.a)throw new Error("Invalid response");document.getElementById("quote").innerText=d.q;document.getElementById("author").innerText="- "+d.a}catch(e){document.getElementById("quote").innerText="Could not load quote"}}document.getElementById("newQuote").addEventListener("click",loadQuote);document.getElementById("copyQuote").addEventListener("click",()=>{const t=document.getElementById("quote").innerText+" "+document.getElementById("author").innerText;navigator.clipboard.writeText(t).then(()=>{const b=document.getElementById("copyQuote");b.innerText="Copied!";setTimeout(()=>b.innerText="Copy",2000)})});loadQuote()'
  },
  {
    id: 'fact-of-day',
    name: 'Fact of the Day',
    category: 'api',
    patterns: [/\b(fact|facts|daily|learn|learning|interesting)\b/i],
    description: 'Get random interesting facts from a free API',
    html: '<div class="app-container"><header><h1>Fact of the Day</h1></header><main><div class="fact-box"><p id="fact">Loading...</p></div><button id="newFact">New Fact</button></main></div>',
    css: '.app-container{max-width:600px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#f093fb,#f5576c);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.fact-box{padding:2rem;background:#f8f9fa;border-radius:8px;margin-bottom:2rem;min-height:100px}.fact-box p{margin:0;font-size:1.1rem;line-height:1.6;color:#333}button{width:100%;padding:0.75rem;background:#f5576c;color:#fff;border:0;border-radius:8px;cursor:pointer;font-weight:600;transition:0.3s}button:hover{transform:translateY(-2px);box-shadow:0 5px 15px rgba(245,87,108,0.4)}',
    js: 'async function load(){try{const r=await fetch("https://uselessfacts.jsonfeed.com/feeds/today");if(!r.ok)throw new Error("API error");const d=await r.json();if(!d.items||d.items.length===0)throw new Error("No data");const fact=d.items[0].summary||d.items[0].content_text||d.items[0].title;if(!fact)throw new Error("No fact");document.getElementById("fact").innerText=fact}catch(e){document.getElementById("fact").innerText="Could not load fact"}}document.getElementById("newFact").addEventListener("click",load);load()'
  },
  {
    id: 'pet-photo-viewer',
    name: 'Pet Photo Viewer',
    category: 'api',
    patterns: [/\b(pet|pets|dog|dogs|animal|animals|photo|photos|picture|pictures)\b/i],
    description: 'View random cute pet photos from the Dog API',
    html: '<div class="app-container"><header><h1>Pet Photos</h1></header><main><div class="photo-container"><img id="photo" src="" alt="Pet" style="display:none"><p id="loading">Loading...</p></div><button id="newPhoto">New Photo</button></main></div>',
    css: '.app-container{max-width:600px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#fa709a,#fee140);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.photo-container{display:flex;align-items:center;justify-content:center;min-height:400px;background:#f8f9fa;border-radius:8px;margin-bottom:2rem;overflow:hidden}#photo{max-width:100%;max-height:100%;border-radius:8px}button{width:100%;padding:0.75rem;background:#fa709a;color:#fff;border:0;border-radius:8px;cursor:pointer;font-weight:600;transition:0.3s}button:hover{transform:translateY(-2px);box-shadow:0 5px 15px rgba(250,112,154,0.4)}',
    js: 'async function load(){try{const r=await fetch("https://dog.ceo/api/breeds/image/random");if(!r.ok)throw new Error("API error");const d=await r.json();if(d.status!=="success"||!d.message)throw new Error("Invalid response");document.getElementById("photo").src=d.message;document.getElementById("photo").style.display="block";document.getElementById("loading").style.display="none"}catch(e){document.getElementById("loading").innerText="Could not load photo"}}document.getElementById("newPhoto").addEventListener("click",load);load()'
  },
  {
    id: 'ip-info-viewer',
    name: 'IP Address Info',
    category: 'api',
    patterns: [/\b(ip\s+address|ip\s+info)\b/i, /\b(ip|address|location|network|info)\b/i],
    description: 'View your IP address and location information',
    html: '<div class="app-container"><header><h1>IP Info</h1></header><main><div id="loading">Loading...</div><div id="info" style="display:none"><div class="info-item"><span class="label">IP Address:</span><span id="ip" class="value">-</span></div><div class="info-item"><span class="label">Country:</span><span id="country" class="value">-</span></div><div class="info-item"><span class="label">City:</span><span id="city" class="value">-</span></div><div class="info-item"><span class="label">ISP:</span><span id="isp" class="value">-</span></div><div class="info-item"><span class="label">Timezone:</span><span id="tz" class="value">-</span></div></div></main></div>',
    css: '.app-container{max-width:500px;margin:0 auto;padding:2rem;background:linear-gradient(135deg,#4facfe,#00f2fe);min-height:100vh;font-family:' + SYSTEM_FONT + '}header{color:#fff;text-align:center;margin-bottom:2rem}h1{margin:0;font-size:2rem}main{background:#fff;border-radius:12px;padding:2rem;box-shadow:0 15px 40px rgba(0,0,0,0.2)}.info-item{display:flex;justify-content:space-between;align-items:center;padding:1rem;background:#f8f9fa;border-radius:8px;margin-bottom:1rem;border-left:4px solid #4facfe}.label{font-weight:600;color:#333}.value{color:#4facfe;font-family:"Courier New",monospace;font-weight:600}#loading{text-align:center;padding:2rem;font-size:1rem;color:#666}',
    js: 'async function load(){try{const r=await fetch("https://ipapi.co/json/");if(!r.ok)throw new Error("API error");const d=await r.json();if(!d.ip)throw new Error("Invalid response");document.getElementById("ip").innerText=d.ip||"-";document.getElementById("country").innerText=d.country_name||"-";document.getElementById("city").innerText=d.city||"-";document.getElementById("isp").innerText=d.org||"-";document.getElementById("tz").innerText=d.timezone||"-";document.getElementById("loading").style.display="none";document.getElementById("info").style.display="block"}catch(e){document.getElementById("loading").innerText="Could not load IP info"}}load()'
  }
];
