/**
 * CodeValidationService
 * Validates code generated by Layout, Styling, and Logic agents
 * Ensures inter-agent compatibility and completeness
 */

export interface ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  details?: {
    extractedIds?: string[];
    extractedClasses?: string[];
    missingElements?: string[];
    orphanedSelectors?: string[];
    orphanedReferences?: string[];
  };
}

export class CodeValidationService {
  /**
   * Validate Layout HTML has all required elements for app type
   */
  static validateLayoutCompleteness(
    html: string,
    requirements: string[]
  ): ValidationResult {
    const errors: string[] = [];
    const warnings: string[] = [];
    const details = {
      extractedIds: [],
      missingElements: [],
    };

    // Extract IDs and classes from HTML
    const { ids, classes } = this.extractHTMLSelectors(html);
    details.extractedIds = ids;

    // Detect app type from requirements
    const appType = this.detectAppType(requirements.join(' '));

    // Check for required elements based on app type
    const requiredElements = this.getRequiredElements(appType);

    for (const required of requiredElements) {
      const found = ids.some((id) => id.toLowerCase().includes(required.toLowerCase())) ||
        classes.some((cls) => cls.toLowerCase().includes(required.toLowerCase()));

      if (!found) {
        errors.push(
          `Missing required element for ${appType}: "${required}" (not found in HTML IDs or classes)`
        );
        details.missingElements!.push(required);
      }
    }

    // Warn if HTML seems incomplete (too few elements)
    if (ids.length < 5 && appType !== 'simple') {
      warnings.push(
        `HTML structure seems minimal (only ${ids.length} elements). App may be incomplete.`
      );
    }

    // Check for common structural issues
    if (!html.includes('<body') && !html.includes('<div')) {
      errors.push('HTML structure missing: no body or container div found');
    }

    return {
      isValid: errors.length === 0,
      errors,
      warnings,
      details,
    };
  }

  /**
   * Validate Styling CSS targets existing HTML elements
   */
  static validateStylingCompatibility(
    html: string,
    css: string
  ): ValidationResult {
    const errors: string[] = [];
    const warnings: string[] = [];
    const details = {
      extractedIds: [],
      orphanedSelectors: [],
    };

    // Extract selectors from CSS
    const cssSelectors = this.extractCSSSelectors(css);

    // Extract IDs and classes from HTML
    const { ids, classes } = this.extractHTMLSelectors(html);
    const htmlSelectors = new Set([...ids, ...classes]);

    // Check each CSS selector targets existing HTML elements
    const orphaned: string[] = [];
    for (const selector of cssSelectors) {
      // Extract the selector part (before {)
      const selectorText = selector.split('{')[0].trim();

      // Check if it's a valid selector that matches HTML
      const selectors = selectorText.split(',').map((s) => s.trim());

      for (const sel of selectors) {
        // Extract ID references (#id)
        const idMatches = sel.match(/#([\w-]+)/g);
        if (idMatches) {
          for (const match of idMatches) {
            const id = match.substring(1);
            if (!ids.includes(id)) {
              orphaned.push(`CSS references non-existent ID: #${id}`);
            }
          }
        }

        // Extract class references (.class)
        const classMatches = sel.match(/\.([\w-]+)/g);
        if (classMatches) {
          for (const match of classMatches) {
            const className = match.substring(1);
            if (!classes.includes(className)) {
              orphaned.push(`CSS references non-existent class: .${className}`);
            }
          }
        }
      }
    }

    if (orphaned.length > 0) {
      errors.push(...orphaned);
      details.orphanedSelectors = orphaned;
    }

    // Warn if CSS is missing
    if (css.trim().length === 0) {
      warnings.push('CSS styling is empty');
    }

    // Warn if CSS is minimal
    if (cssSelectors.length < 3) {
      warnings.push(`CSS has only ${cssSelectors.length} selectors (expected at least 3)`);
    }

    return {
      isValid: errors.length === 0,
      errors,
      warnings,
      details,
    };
  }

  /**
   * Validate Logic JS references existing HTML elements
   */
  static validateLogicCompatibility(
    html: string,
    js: string
  ): ValidationResult {
    const errors: string[] = [];
    const warnings: string[] = [];
    const details = {
      extractedIds: [],
      orphanedReferences: [],
    };

    // Extract IDs from HTML
    const { ids, classes } = this.extractHTMLSelectors(html);
    details.extractedIds = ids;

    // Extract element references from JavaScript
    const jsReferences = this.extractJSElementReferences(js);

    // Check each JS reference targets existing HTML elements
    const orphaned: string[] = [];
    for (const ref of jsReferences) {
      if (!ids.includes(ref) && !classes.includes(ref)) {
        orphaned.push(`JavaScript references non-existent element: "${ref}"`);
      }
    }

    if (orphaned.length > 0) {
      errors.push(...orphaned);
      details.orphanedReferences = orphaned;
    }

    // Check for common issues
    if (js.includes('TODO') || js.includes('FIXME')) {
      warnings.push('JavaScript contains TODO/FIXME comments - implementation may be incomplete');
    }

    if (!js.includes('function') && !js.includes('const') && !js.includes('let')) {
      warnings.push(
        'JavaScript appears to have no function or variable definitions - may be incomplete'
      );
    }

    // Warn if JS is missing
    if (js.trim().length === 0) {
      warnings.push('JavaScript logic is empty');
    }

    // Check for event listeners
    const eventListeners = (js.match(/addEventListener|onclick|on\w+\s*=/gi) || []).length;
    const buttons = (html.match(/<button|<input[^>]*type\s*=\s*["']button/gi) || []).length;

    if (buttons > 0 && eventListeners === 0) {
      warnings.push(
        `HTML has ${buttons} button(s) but JavaScript has no event listeners - buttons may not work`
      );
    }

    return {
      isValid: errors.length === 0,
      errors,
      warnings,
      details,
    };
  }

  /**
   * Extract all IDs and classes from HTML
   */
  static extractHTMLSelectors(html: string): { ids: string[]; classes: string[] } {
    const ids: string[] = [];
    const classes: string[] = [];

    // Extract IDs: id="value" or id='value'
    const idMatches = html.match(/id\s*=\s*["']([^"']+)["']/gi);
    if (idMatches) {
      for (const match of idMatches) {
        const id = match.match(/["']([^"']+)["']/)?.[1];
        if (id) ids.push(id);
      }
    }

    // Extract classes: class="value" or class='value'
    const classMatches = html.match(/class\s*=\s*["']([^"']+)["']/gi);
    if (classMatches) {
      for (const match of classMatches) {
        const classList = match.match(/["']([^"']+)["']/)?.[1];
        if (classList) {
          const classNames = classList.split(/\s+/);
          classes.push(...classNames);
        }
      }
    }

    return { ids: [...new Set(ids)], classes: [...new Set(classes)] };
  }

  /**
   * Extract all ID references from JavaScript
   */
  static extractJSElementReferences(js: string): string[] {
    const references: string[] = [];

    // Extract getElementById('...')
    const getElementMatches = js.match(/getElementById\(['"]([^'"]+)['"]\)/g);
    if (getElementMatches) {
      for (const match of getElementMatches) {
        const id = match.match(/['"]([^'"]+)['"]/)?.[1];
        if (id) references.push(id);
      }
    }

    // Extract querySelector('#...')
    const querySelectorMatches = js.match(/querySelector\(['"]#([^'"]+)['"]\)/g);
    if (querySelectorMatches) {
      for (const match of querySelectorMatches) {
        const id = match.match(/['"]#([^'"]+)['"]/)?.[1];
        if (id) references.push(id);
      }
    }

    // Extract querySelector('...') with IDs
    const queryMatches = js.match(/querySelector\(['"]([^'"]*#[^'"]*)['"]\)/g);
    if (queryMatches) {
      for (const match of queryMatches) {
        const selector = match.match(/['"]([^'"]+)['"]/)?.[1];
        if (selector) {
          const id = selector.match(/#([\w-]+)/)?.[1];
          if (id) references.push(id);
        }
      }
    }

    return [...new Set(references)];
  }

  /**
   * Extract all CSS selectors
   */
  static extractCSSSelectors(css: string): string[] {
    const selectors: string[] = [];

    // Split by { to get selector part
    const rules = css.split('{');

    for (let i = 0; i < rules.length - 1; i++) {
      // Get the last line of the rule (selector)
      const lines = rules[i].split('\n');
      const selector = lines[lines.length - 1].trim();
      if (selector && !selector.includes(';')) {
        selectors.push(selector + '{...}');
      }
    }

    return selectors;
  }

  /**
   * Detect app type from description
   */
  private static detectAppType(description: string): string {
    const lower = description.toLowerCase();

    if (/calculator|math|arithmetic|compute|operation/i.test(lower)) return 'calculator';
    if (/todo|task|checklist|list|item/i.test(lower)) return 'todo';
    if (/weather|forecast|temperature|climate/i.test(lower)) return 'weather';
    if (/ecommerce|shop|cart|store|product|buy|sell/i.test(lower)) return 'ecommerce';
    if (/dashboard|analytics|chart|graph|metric|report/i.test(lower)) return 'dashboard';
    if (/form|input|contact|survey/i.test(lower)) return 'form';

    return 'generic';
  }

  /**
   * Get required elements for app type
   */
  private static getRequiredElements(appType: string): string[] {
    const requirements: { [key: string]: string[] } = {
      calculator: [
        'display',
        'button',
        'number',
        'operator',
        'equal',
        'clear',
      ],
      todo: [
        'input',
        'button',
        'add',
        'list',
        'item',
        'delete',
        'clear',
      ],
      weather: [
        'search',
        'input',
        'button',
        'display',
        'forecast',
        'temperature',
        'condition',
      ],
      ecommerce: [
        'product',
        'image',
        'price',
        'button',
        'cart',
        'add',
        'item',
        'total',
      ],
      dashboard: [
        'chart',
        'graph',
        'metric',
        'data',
        'display',
        'container',
      ],
      form: [
        'input',
        'form',
        'button',
        'submit',
        'label',
      ],
      simple: [], // No specific requirements
    };

    return requirements[appType] || requirements['generic'];
  }
}
